swagger: "2.0"
info:
  version: "0.0.1"
  title: Kaplan node server
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /api/course/upcoming:
    # our controller name
    x-swagger-router-controller: course
    get:
      operationId: getUpcomingCourses
      description: Get upcoming course information
      produces:
         - application/json
      # movie info to be stored
      parameters:
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GeneralResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
        description: Error message
      error:
        type: object
        description: Additional detail about the error if available
  GeneralResponse:
    type: object
    properties:
      message:
        type: string
        description: success
      data:
        type: array
        items:
          $ref: '#/definitions/UpcomingCourse'
        description: data
    required:
      - success
      - description
  UpcomingCourse:
    type: object
    properties:
      title:
        type: string
        description: Title of the course
      description:
        type: string
        description: Description of the course
      instructorName:
        type: string
        description: Name of the instructor
      instructorPhotoUrl:
        type: string
        description: URL for the instructor's thumb image
      subjectPhotoUrl:
        type: string
        description: URL for the courses thumb image
      time:
        type: string
        description: Time at which the course starts
